apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rian2oezj-go 
  janus-idp.io/tekton: rian2oezj-go
  backstage.io/kubernetes-id: rian2oezj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rian2oezj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  